// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changedbremovedevicesandrulestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedbremovedevicesandrulestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201711090812389_Change db remove devices and rules table ;("; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
