// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeuserProfiletableremoveagefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeuserProfiletableremoveagefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051440588_change userProfile table remove age field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
